### ISSUE TITLE
Can't login to gcloud

### ISSUE THREAD

**Issue by vladimirgorealionstep** [elgohr/gcloud-login-action#8]
Following the exact flow in the readme.md. Using a key from a service account that has all permissions for docker registry. Getting this
```
Run elgohr/gcloud-login-action@v1
  with:
    account_key: ***
  ...
base64: invalid input
```

**Comment by elgohr** [comment]
So you also read this line? (https://github.com/elgohr/gcloud-login-action#mandatory-arguments)
> **Base64 encoded** service account key exported as JSON

**Comment by vladimirgorealionstep** [comment]
Missed that, thanks!
